# Generated by Django 4.2.5 on 2023-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_status',
            name='timestamp_utc',
            field=models.TextField(),
        ),
    ]
