# Generated by Django 4.2.5 on 2023-09-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0002_alter_store_status_timestamp_utc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store_status',
        ),
    ]
