# Generated by Django 4.2.5 on 2023-09-23 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0008_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_status',
            name='timestamp_utc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
